version: 2.1
orbs:
  slack: circleci/slack@3.4.2

jobs:
  build:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:stitch-tap-tester
    steps:
      - checkout
      - run:
          name: 'Setup virtual env'
          command: |
            python3 -mvenv /usr/local/share/virtualenvs/tap-tap-crossbeam
            source /usr/local/share/virtualenvs/tap-tap-crossbeam/bin/activate
            pip install -U pip setuptools
            pip install .[dev]
      - run:
          name: 'JSON Validator'
          command: |
            source /usr/local/share/virtualenvs/tap-tester/bin/activate
            stitch-validate-json tap_tap-crossbeam/schemas/*.json
      - run:
          name: 'pylint'
          command: |
            source /usr/local/share/virtualenvs/tap-tap-crossbeam/bin/activate
            pylint tap_tap-crossbeam --disable 'broad-except,chained-comparison,empty-docstring,fixme,invalid-name,line-too-long,missing-class-docstring,missing-function-docstring,missing-module-docstring,no-else-raise,no-else-return,too-few-public-methods,too-many-arguments,too-many-branches,too-many-lines,too-many-locals,ungrouped-imports,wrong-spelling-in-comment,wrong-spelling-in-docstring,bad-whitespace'
      - run:
          name: 'Integration Tests'
          command: |
            aws s3 cp s3://com-stitchdata-dev-deployment-assets/environments/tap-tester/tap_tester_sandbox dev_env.sh
            source dev_env.sh
            source /usr/local/share/virtualenvs/tap-tester/bin/activate
            pip install .[dev,test] # Install tap for the test client subclass usage
            run-test --tap=tap-tap-crossbeam tests
      - slack/status:
          channel: 'stitch-tap-tester-tests'
          mentions: "${CIRCLE_USERNAME}"
          fail_only: true
          only_for_branches: master
          failure_message: |
            :red_circle: ${CIRCLE_JOB} failed!

workflows:
  commit: &commit_jobs
    jobs:
      - build:
          context:
            - circleci-user
            - tap-tester-user
  build_daily:
    <<: *commit_jobs
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
